Repository stolostron/multicluster-controlplane, pull requests merged in 2023-01, with the labels that each got.

#2 add demo scripts
  Makefile
  hack/demo/README.md
  hack/demo/demo-magic.sh
  hack/demo/next-generation.sh
  hack/deploy-multicluster-controlplane.sh
  hack/deploy/controlplane/deployment.yaml
  hack/deploy/controlplane/kustomization.yaml
  hack/deploy/controlplane/route.yaml
  hack/deploy/controlplane/service.yaml
  test/scripts/cleanup-e2e.sh
  test/scripts/setup-e2e.sh
Labels: lgtm, approved

#3 enable external etcd for e2e and update readme
  Makefile
  README.md
  hack/deploy-etcd.sh
  hack/deploy/controlplane/external-etcd-patch.yaml
  hack/deploy/etcd/kustomization.yaml
  hack/deploy/etcd/statefulset.yaml
  hack/deploy/etcd/statefulsetservice.yaml
  test/scripts/setup-e2e.sh
Labels: lgtm, approved

#5 Make demo scripts work
  hack/demo/README.md
  hack/demo/next-generation.sh
  hack/lib/etcd.sh
  hack/lib/init.sh
  hack/lib/logging.sh
  hack/lib/util.sh
Labels: lgtm, approved

#6 fixed test issues for running prow
  .gitignore
  Makefile
  cmd/server/main.go
  go.mod
  go.sum
  hack/deploy/controlplane/deployment.yaml
  hack/deploy/controlplane/external-etcd-patch.yaml
  pkg/controllers/controller.go
  test/scripts/setup-e2e.sh
Labels: lgtm, approved

#8 start standalone controlplane
  .gitignore
  Makefile
  README.md
  hack/deploy-multicluster-controlplane.sh
  hack/deploy/controlplane/deployment.yaml
  hack/deploy/controlplane/kustomization.yaml
  hack/start-multicluster-controlplane.sh
  test/scripts/setup-e2e.sh
Labels: lgtm, approved, dco-signoff: no

#10 update readme to add KinD dependency
  hack/demo/README.md
Labels: lgtm, approved, dco-signoff: yes

#9 fix e2e test
  Makefile
  test/scripts/prow-e2e.sh
  test/scripts/setup-dep.sh
  test/scripts/setup-e2e.sh
Labels: lgtm, approved, dco-signoff: yes
